version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: trello_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: trello_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trello_network

volumes:
  postgres_data:

networks:
  trello_network:
    driver: bridge
